### ISSUE TITLE
Where does `set-log-location` come from?

### ISSUE THREAD

**Issue by kongakong** [stevecrozz/shentrypoint#1]
At line 89, https://github.com/stevecrozz/shentrypoint/blob/master/entrypoint#L89 there is a function call `set-log-location`. Where does it come from?

Thanks for a great script BTW

**Comment by stevecrozz** [comment]
Strange that I didn't notice this comment until today. That line came from a larger project which did some things that were specific to my last company. I mean to remove all that and it looks like I left something in by mistake. I'm going to remove it, and thanks for finding it!
